spring.application.name=flujodefondos

#spring.datasource.url=jdbc:postgresql://aws-0-us-east-2.pooler.supabase.com:6543/postgres?user=postgres.zenxfywhcmkasajilwxa&password=[8wMLR2rkArGSyfMk]
#spring.datasource.driver-class-name=org.postgresql.Driver

#spring.datasource.url=jdbc:mysql://localhost:3306/flujo_de_fondos
#spring.datasource.username=root
#spring.datasource.password=
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.datasource.url=jdbc:sqlite:./database/flujo_de_fondos.db
spring.datasource.driver-class-name=org.sqlite.JDBC

# Pool de conexiones
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.maximum-pool-size=1